version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "${GITHUB_WORKSPACE}/config:/etc/selenoid"  # Adjusted to use environment variable
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${GITHUB_WORKSPACE}/video:/opt/selenoid/video"  # Adjusted to use environment variable
      - "${GITHUB_WORKSPACE}/logs:/opt/selenoid/logs"  # Adjusted to use environment variable
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
