name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenoid:
        image: aerokube/selenoid:latest-release
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
          cache: maven

      - name: Set environment variable for Docker
        run: echo "GITHUB_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull latest Chrome image
        run:  docker pull selenoid/chrome:latest

      - name: Start Selenoid
        run: docker-compose up -d

      - name: Run Maven Tests
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Stop Selenoid
        run: docker-compose down

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
